export const GET_ALL_QUESTIONS_SAGA = 'GET_ALL_QUESTIONS_SAGA'
export const GET_ANSWERS_BY_QUESTION_ID_SAGA = 'GET_ANSWERS_BY_QUESTION_ID_SAGA'
export const LOGIN_SAGA = 'LOGIN_SAGA'
export const LOGOUT_SAGA = 'LOGOUT_SAGA'